### ISSUE TITLE
Gamescope runs fine, when it works then starts to stutter very badly on Fedora KDE

### ISSUE THREAD

**Issue by Melorn366** [Plagman/gamescope#163]
What repository did I use in order to install the latest gamescope on fedora ? This https://copr.fedorainfracloud.org/coprs/petrb/gamescope/packages/
 
Why did I use this repository when fedora is available in the main repository? Because this issue was present with older gamescope builds (which is available on fedora) 

What else do I notice during the time when the Bug happens?

GPU usage is 100% all the time.

What others programs do I use in order to make gamescope run at the best performance?
Corectrl (to control gpu fancurve and set the gpu governor to performance along with cpu), gamemode (So that I can force the CPU to have a higher priority during steam gameplays. In gamemode.ini file i set renice to 10, desiredgov set to performance and finally softrealtime to auto  )

Does this issue occur  when gamemoded is not in use (deleted from the game launch section).  Yes it happens. With the newer gamescope version and the older one which is available in fedora.

What files should I provide, so this issue could be sorted ?

**Comment by petr666** [comment]
Hi, this is my repository, so only for clarification, despite package has version 3.7.1, it is actually built from master so it matches commit d537d6ac98fe6eccafda206dec0dd99c337f648c. I did not encounter this bug yet, but i am not using it very much, i was testing some games maybe for 30 minutes or so.

**Comment by Melorn366** [comment]
@petr666  Hi there check out my video about this. 
launch option  gamescope -w 1920 -h 1080 gamemoderun %command%

https://www.youtube.com/watch?v=i_09HOxnhJg

**Comment by Kiwii** [comment]
> In gamemode.ini file i set renice to 10

10 or -10? Higher nice value means lower priority.

**Comment by Melorn366** [comment]
> > In gamemode.ini file i set renice to 10
> 
> 10 or -10? Higher nice value means lower priority.

Accodin to this webside (you are wrong) https://gamecrate.com/linux-gaming-boost-your-performance-gamemode/25200
Quote
"f you have four or more CPU cores. I like to set the “renice” value at “10” - this will increase the priority of your game’s process, telling Linux to prioritize the game’s CPU time."

**Comment by Melorn366** [comment]
The issue is still present. Its definitely not caused by gamemode. For further testing purpose I deleted gamemode from my system, and just let gamescope run without even moving a mouse in menu. The issue appeared precisely at 30 mins. I tested this stock kernel (without any patches) and with custom tkg patches. The issue could have been reproduced at both times. So no matter what Desktop environment I use, it happens all the time. Tested on Fedora, Ubuntu, Arch, variants like (endeavour, garuda) . This issue still persist.

**Comment by Melorn366** [comment]
As I said I would love to provide logs or anything that the dev needs. I just need explanation how to provide them.

**Comment by emersion** [comment]
Maybe trying to capture some traces with gpuvis when it's stuttering would help.

**Comment by Melorn366** [comment]
Okay. Figured it out that gpuvis is your tool emersion. Buit it using aur repo. Now how to find traces when it comes to steam games? Or how does it work? I would gladly help. I just need explanation.

**Comment by ppascher** [comment]
Have the same issue with "The Witcher 3". After ~24 minutes the game starts stuttering. FPS according to MangoHud drop from ~160 to ~80. Restarting the game helps (for another 24 minutes). If I start the game without gamescope the issue is gone. Running under Windows is fine as well. I tried different Proton Versions but it did not make a difference. This is on kernel 5.12.4 and mesa-git (as of 2021-05-15). Will try to get some traces/logs.

**Comment by ppascher** [comment]
Not sure if this is the same issue as the OP but the symptoms describe my issue. Here is a trace-cmd capture right after it started stuttering.
[witcher3_trace-cmd.dat.tar.gz](https://github.com/Plagman/gamescope/files/6489119/witcher3_trace-cmd.dat.tar.gz).
Frametimes start looking like this instead of a constant value/line:
![20210516-131356_swappy](https://user-images.githubusercontent.com/10400581/118395374-5c75ef00-b64a-11eb-84ae-56cb3f534735.png)

**Comment by ppascher** [comment]
Tried some more games. The stuttering appears after the 24 minute mark for 
The Witcher3 (DXVK)
Cyberpunk 2077 (VKD3D)
Doom Eternal (Vulkan)
Book of Forbidden Tales 2 (OpenGL)

It does not seem to be temperature related as those are pretty stable after 10 minutes. To test I ran all fans at 100% speed which dropped the temperatures by 5-8°C but the issue still appeared after 24 minutes. And as mentioned before: without gamescope all those games work fine while having the same temperature.

**Comment by ppascher** [comment]
Still is an issue with latest master on my machine (arch 5.14.2, mesa-git):
Tried a trace-cmd capture again (as last one did not contain required info from what @emersion told me in irc):
[20210908_witcher3_trace-cmd.dat.tar.gz](https://github.com/Plagman/gamescope/files/7128568/20210908_witcher3_trace-cmd.dat.tar.gz)
gpuvis screenshot of when the stuttering starts:
![image](https://user-images.githubusercontent.com/10400581/132503834-3a2c6d85-b978-4a97-9b91-928c027d8b45.png)

**Comment by ppascher** [comment]
I just tried starting two games via gamescope with a 10 minute delay. Both windows ran next to each other on one screen (sway tiled mode). The first game (Kingdom Come Deliverance via DXVK) started stuttering as expected after ~24 minutes. The second game (Witcher3 / DXVK) ran fine for another 10 minutes and then also started stuttering.
If I use the same setup but switch to a different workspace on the same monitor so that the games are not visible they run fine even after the 24 minute mark. So it appears the games have to be visible for 24 minutes for the bug to kick in.

**Comment by Melorn366** [comment]
Greetings ppacher.  Yes we have the same issue. To be precise exactly the same ! Finally someone !

I am very worried about this issue. If steamdeck releases and this issue will be still present in December. Steamdeck will fail miserably. I truly wish team valve the best. But this issue haven't been fixed for half a year now. 

This information is not reaching either Emerson or Plagmen ( Pierre-Loup A. of Valve)

BTW thx for sharing ppascher.

**Comment by ppascher** [comment]
I run at 3440x1440 and tried both `-W/-H` and `-w/-h`. I do not use `-n`. I tried running with and without gamemode/mangohud. I manually fullscreen my game as with the `-f` option games do not run. I use git master of sway/wlroots/mesa on arch. Tried both custom kernel and default distro kernel. Hopefully we can figure out what is causing this.

**Comment by Melorn366** [comment]
Hey there ppasher, thx for the reply. I don't know what it is causing this, but it concerns me that plagman or emerson doesn't respond. Can you contact them ? They doesn't seem to notice our conversation..This is very serious bug.

**Comment by emersion** [comment]
This is an open-source project. Feel free to submit patches, but don't expect your bugs to magically fixed.

I don't have time to look into your issue at the moment.

**Comment by Melorn366** [comment]
@emersion Greetings thx for responding.  This has been an issue for months now and I pretty much bad at programming. But lets ask @ppascher 

Btw emersion what kind of data do you need in the future in order for this to be fixed?

**Comment by ppascher** [comment]
One more thing I noticed is when I keep moving the mouse the stuttering is gone. As soon as I stop the cursor the stuttering is back.

**Comment by ppascher** [comment]
In case anyone else runs into this and is able to make sense of it here is another gpuvis screenshot of a trace with gamescope events logged while stuttering:
![20211017-221126_gpuvis](https://user-images.githubusercontent.com/10400581/137643486-3b4951ca-d200-464f-8c43-41dca457f06e.png)
And here is the full trace file:
[20211017_gamescope_trace-cmd.dat.tar.gz](https://github.com/Plagman/gamescope/files/7360767/20211017_gamescope_trace-cmd.dat.tar.gz)

**Comment by ppascher** [comment]
some more information:
starting steam via gamescope (either from within sway or directly from tty with `/usr/local/bin/gamescope -e -f -- steam -tenfoot -steamos -fulldesktopres` and then a steam game does not cause these stutters.
Starting steam from within sway without gamescope and then using the steam game launch options to start a game via gamescope causes these stutters after ~24-25 minutes.

**Comment by jarrard** [comment]
ARK goes into stutter mode after 20mins with gamescope, no idea whats going on.

**Comment by jarrard** [comment]
I just remembered; I believe this stutter happens with gamescope and Star Citizen (via wine). So that is yet another game that gets this bug and surely a solution can be found.

**Comment by Plagman** [comment]
@ppascher interesting trace, thanks a lot! Looks like something is keeping the steamcompmgr thread busy for a long time. This would be great to look at such a trace with latest gpu-trace, which also includes a perf capture.

Separate from that, worth re-testing with current master, as the buffer import path has changed significantly and might interact with this issue.

**Comment by ppascher** [comment]
@Plagman Sorry, did not get a notification and just now saw your reply. I just tested with kernel 5.15.11, mesa, wlroots, gamescope git master as of today and still run into this issue. I created a new capture using gpu-trace and sent you a download link through the valvesoftware contact page.
This trace shows the stuttering and also a brief period where the stutter was reduced when I kept moving the mouse.
Thank you for looking into this.

**Comment by JPEspinoza** [comment]
Hello, I don't know if this is related, but someone on Reddit asked me to mention it here.

On Fedora 35 with Gnome, Nvidia and Xorg (**no** Gamescope), when I play Valheim (Native, Vulkan) it starts stuttering after about 30 minutes unless I **enable** the Steam overlay, which seems to workaround the bug. To be clear: Steam overlay disabled = stuttering and low FPS after ~30 minutes, Steam overlay enabled = normal performance. I don't need to open the overlay in game either, just having it be enabled works. I do have an FPS counter though.

Maybe the Steam overlay has something to do with this issue? Or whatever it does bypasses the error? Again, I'm not using Gamescope, so its probably a completely different issue specific to Valheim.

More people mentioning the bug in this thread: https://www.reddit.com/r/linux_gaming/comments/lmslz9/best_settings_to_optimize_valheim/

**Comment by jarrard** [comment]
I do believe Mortal Online 2 stutters with gamescope after 20mins or so. I noticed at main menu a distinct mouse cursor stutter (can't get into game due to queue, but yeah, stutter).

Sure hope this stutter issue can be resolved. Kind of makes GS pointless otherwise, and it may also occur on steamdeck once in peoples hands.

**Comment by Melorn366** [comment]
Yup the problem still exists. So weird. Only AMD GPU card are affected,
with Intel processor ?

**Comment by jarrard** [comment]
AMD 5700G and 6800XT here.

**Comment by Melorn366** [comment]
Well then it seems that It is not a build specific problem, at one point,
since you use AMD processor and still has it. But on the other hand, we
both use AMD GPU (or maybe this is a stupid question from me from the
start). Gamescope could be run only on AMD GPUs right?

**Comment by zoktiik** [comment]
I've had multiple games give me this same issue. My system is running Fedora Workstation 35 with the `sentry/kernel-fsync` and `gloriouseggroll/mesa-aco` coprs enabled (though I still had the issue with the ones from the official Fedora repositories). I installed KDE alongside the stock GNOME, still using gdm as my display manager, but stopped using KDE due to a very bad bug with kwin involving how it handles fullscreen apps (system failure when one loses focus). 

Right now, I'm using GNOME on X11 and continue to have this issue with any game I run under gamescope. I have the "disable unredirect fullscreen windows" extension installed. Generally, I tend to run my games with mangohud, gamemode, and FSR enabled. Mangohud showing the frametime issue is weird -- it shows up in Sleeping Dogs DE and Risk of Rain 2 as that same series of spikes, but on Dishonored 1 the frametime graph remains a flatline while the frametime issue remains obvious.

My version of gamescope is from the official Fedora repositories, version `3.8.4`. In my launch options I have `gamescope` and its arguments first, then the Wine AMD FSR environment variables, then `mangohud` and `gamemoderun`. I generally use Proton-7.0rc6-GE-1 to run my games. I have an AMD Ryzen 9 3900X CPU and an AMD RX 5700 XT GPU. 

I hope this information helps to figure out the root cause of this issue. If any more information about my setup is needed, please feel free to ping me.

**Comment by cactushydrocodone** [comment]
This is most likely not a gamescope, but an AMD issue, as my pc crashes after i exit the game. Very similar to the crashes i had on windows with amd too. I could try mesa from mesa-git, maybe its fixed there

**Comment by ilievi187** [comment]
Hi , guys i have to inform everyone , gamescope works perfectly fine now..
However don't forget to install the Black Mesa package (gperftools) . I
can't use it right now because i am mostly playing CS:GO competitive and
there is some kind of delay i am feeling it when i use gamescope with fsr ,
i am gonna test tomorrow without AMD FSR just to be sure that is only from
gamescope.

**Comment by zoktiik** [comment]
Hello, @ilievi187. Would you be willing to give your OS name and version, as well as your version of gamescope? It's possible you're not currently running on a system that is affected by this bug.

**Comment by ilievi187** [comment]
Zoktik i am running Arch Rolling , there is no bugs except little bit of
mouse delay ,just a little little tiny bit most of the users are not going
to notice it .

**Comment by zoktiik** [comment]
> Zoktik i am running Arch Rolling

@ilievi187 Alright, that's good to know. What is your version of gamescope? 
Also, could you please tell us the last version of gamescope that was causing the stuttering issues for you? That's if you can remember it, or find it in your system logs.

**Comment by madmonki** [comment]
Any solutions? I get this issue on Apex and Elden Ring but probably I will get on every game. My launch options are gamemoderun gamescope -e -f -- %command% . Distro is Endeavour (arch btw) and using kde-wayland.

**Comment by cactushydrocodone** [comment]
The issue just disappeared for me. Im on arch, maybe an update of some package fixed it

**Comment by madmonki** [comment]
> Hello, I don't know if this is related, but someone on Reddit asked me to mention it here.
> 
> On Fedora 35 with Gnome, Nvidia and Xorg (**no** Gamescope), when I play Valheim (Native, Vulkan) it starts stuttering after about 30 minutes unless I **enable** the Steam overlay, which seems to workaround the bug. To be clear: Steam overlay disabled = stuttering and low FPS after ~30 minutes, Steam overlay enabled = normal performance. I don't need to open the overlay in game either, just having it be enabled works. I do have an FPS counter though.
> 
> Maybe the Steam overlay has something to do with this issue? Or whatever it does bypasses the error? Again, I'm not using Gamescope, so its probably a completely different issue specific to Valheim.
> 
> More people mentioning the bug in this thread: https://www.reddit.com/r/linux_gaming/comments/lmslz9/best_settings_to_optimize_valheim/

It appears the bug gone with this solution. My steam overlay was off.

**Comment by ppascher** [comment]
> It appears the bug gone with this solution. My steam overlay was off.

Enabling steam overlay prevents the issue for me as well. Tested in both DXVK (Kingdom Come Deliverance) and VKD3D (Cyberpunk 2077). Thank you @JPEspinoza

**Comment by itspngu** [comment]
I can confirm that enabling the Steam overlay "fixes" the issue. I'm on Fedora (Rawhide) aswell.

**Comment by itspngu** [comment]
It's related to `-e/--steam`, which I had in my commandline because my cursor wasn't working as reported by others in #420. Removing that and using Proton 6.3 instead of 7 (tried both Experimental and GE) allows me to turn off the Steam overlay and not have the degradation after 24 minutes.

/cc @Plagman

**Comment by kindagoose** [comment]
I have this issue with proton games, but same games in native mode seem to work perfectly fine.

arch, nvidia, all up to date

**Comment by kindagoose** [comment]
it seems like i managed to fix my stuttering issues by adding -r 240 (my screen in 60hz, more on that down below)

In one of the games i noticed that __GL_SHOW_GRAPHICS_OSD=1 did show me that gamescope window is running at 60fps and vsync is on (game has vsync off, ingame limiter is at 120, i use i3 without compositor), then i notices that this game only allows to choose 59hz for the "fullscreen" mode, i added -r 240 and this mode was changed to 239hz, stutters were gone as well. Tho __GL_SHOW_GRAPHICS_OSD=1 still shows 60fps and vsync on. I tested it on both native OpenGL and Proton DXVK games.

in description it says that fps limit is disabled by default but it seems like it is still limited to monitors refresh rate: https://github.com/Plagman/gamescope/issues/304

**Comment by mystrdat** [comment]
Same issue in Back 4 Blood on Fedora Silverblue 37 flatpak gamescope/steam versions, using `-f` and `-r` flags, 6700 XT GPU. Game runs fine for a while and ~30 minutes later the frame timing jumps up and down with extreme unplayable stutters. Whether I set max_fps or v-sync in game doesn't seem to matter.

**Comment by madmonki** [comment]
you should have -e in flags and enable steam overlay. @mystrdat

**Comment by CartoonFan** [comment]
Ran into this issue too, unfortunately :cry:

Nvidia GTX 960, Ryzen 3700X, Arch Linux, Castlevania Advance Collection, Proton-tkg 7.18.r11.gaabde227, Linux 5.19.14-270-tkg-bmq

Here's my Steam launch options:
> gamescope -w 1280 -h 720 -r 60 -o 60 -n -i -Y -e -- obs-gamecapture %command%

And here are the proton logs:
[steam-1552550_gamescope_no_overlay.log](https://github.com/Plagman/gamescope/files/9803459/steam-1552550_gamescope_no_overlay.log)
[steam-1552550_no_gamescope_no_overlay.log](https://github.com/Plagman/gamescope/files/9803464/steam-1552550_no_gamescope_no_overlay.log)

I'm running vk-capture, but I can't imagine the problem is there, right? For me, the time limit is about 27-28 minutes before the stuttering starts. I don't have concrete proof, but I suspect that the game window needs to be in focus for the stuttering to happen; I feel like the game was running for >28 minutes with no problem, but after about...maybe 11 minutes of in-focus gameplay, the stutters happened.

Anyway, I'm happy to provide more information if it'll help :+1:

**Comment by CartoonFan** [comment]
I managed to take a picture with MangoHud running (sorry for the tiny font :rofl:) :

![2022-10-23_21-37_gamescope_stutter](https://user-images.githubusercontent.com/29664894/197460648-4ade32a7-a568-468d-85bd-ad039737b7e6.png)

Like before, the stutters happened after somewhere between 95-96K frames--roughly 28 minutes of gameplay. Curiously, GPU usage seems to be **reduced** after the stutters begin; it went from 20-30% usage to 10-20% usage :confused: .

I also managed to get some logs (again, from MangoHud):

[game_2022-10-23_23-15-07.csv](https://github.com/Plagman/gamescope/files/9849202/game_2022-10-23_23-15-07.csv)

[game_2022-10-23_23-15-07_summary.csv](https://github.com/Plagman/gamescope/files/9849203/game_2022-10-23_23-15-07_summary.csv)

There seems to be a bunch of weird 14 FPS dips surrounded by normal FPS rates :thinking:

My gamescope params are here:
>  -w 1600 -h 900 -W 1600 -H 900 -r 60 -o 60 -i -n -Y -e

I'd really love to see a fix that's not just "turn on the steam overlay" :pray:

(Also, IMO, this bug is up there with #216 and #577 for me...but those I can kind of work around :laughing:)

**Comment by Sturmlocke86** [comment]
Same issue here on Ubuntu 22.10 and Nvidia T600 with 515 drivers installed. Going to try the suggested launch command addition -e plus will also enable Steam Overlay, as I usually turn Steam Overlay off, and report back how it goes. Installed Gamescope via Ubuntu 22.10 repos.

**Comment by Sturmlocke86** [comment]
Update

Ok, doing what the others suggested "fixed" the issue on my end as well: Activate Steam Overlay, add -e line to Gamescope launch command in Steam, use Proton 6, 7 or Exp - works with all of them. Performance is more or less normal after this. Usable workaround for now, but not optimal when recording or streaming via OBS ofc. That said, wouldn't mind donating a few coins to fix this.

**Comment by justin8** [comment]
Sadly this issue still exists for me; when I enable steam overlay with or without the `-e` I get a black window (despite using the fullscreen flag in the gamescope command) and it never loads.

**Comment by hikkidev** [comment]
@Melorn366 please, rename this issue to make it easier to find

**Comment by Sporknife** [comment]
I still experience this issue when using gamescope.

Operating System: Arch Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.102.0
Qt Version: 5.15.8
Kernel Version: 6.1.9-arch1-1 (64-bit)
Graphics Platform: Wayland
Processors: 12 × Intel® Core™ i7-8700 CPU @ 3.20GHz
Memory: 15,5 GiB of RAM
Graphics Processor: AMD Radeon RX 480 Graphics
Mesa: 22.3.4-1, 23.1 (chaotic-aur)

**Comment by cheungyau2022** [comment]
I am having the same issue. Ubuntu 22.04 with Nvidia Tesla P40. Games run fine for around half an hour, then frame drops severely, and frame time goes crazy. Without gamescope all games run perfectly. I will try enabling steam overlay and adding -e option.

**Comment by zaskokus** [comment]
> > It appears the bug gone with this solution. My steam overlay was off.
> 
> Enabling steam overlay prevents the issue for me as well. Tested in both DXVK (Kingdom Come Deliverance) and VKD3D (Cyberpunk 2077). Thank you @JPEspinoza

out of curiosity, what are your parameters to run KCD over gamescope? No matter what I do the game doesn't start (leaving wine components hanging and requiring to be killed manually). I get the splash screen and then nothing.

**Comment by GrabbenD** [comment]
How can I use GPUVIS to generate a graph with the right values to debug stutter (@ppascher mentioned that @emersion provided the correct commands in a IRC channel)? For reference, I'm using amdgpu with Mesa

**Comment by bhavdeepsingh** [comment]
Getting this issue with non steam games on steam deck. Does anyone have an idea of what workaround might work there? Disabling the overlay on game mode doesn’t appear to be a thing

**Comment by sharkautarch** [comment]
> Getting this issue with non steam games on steam deck. Does anyone have an idea of what workaround might work there? Enabling the overlay in game mode doesn’t appear to be a thing
> 
> Reddit thread: https://www.reddit.com/r/SteamDeck/s/KZ9lKAOLtw

Looking at the reddit thread, looks like at some points there's a spike in one of the cpu cores (see time 0:02 of the video, time 0:04)... 
Not sure if gamescope is the actual process causing the spike, or if it is the game...
Also maybe the games you're having issues with are just non-vulkan/non-d3d games? which would be significant because normally gamescope is forced to pass frames thru Xwayland for non-vulkan/non-d3d games...

If you can look at the terminal/stdout output of gamescope, you should be able to check if gamescope is able to *bypass* Xwayland by seeing if it prints lines that start with: `[Gamescope WSI]`
Not sure how you find the terminal/stdout output of gamescope on the steam deck, ask @Joshua-Ashton if you don't know

If you determine that the problem is with games where gamescope *isn't able to bypass* Xwayland, then try launching said games with: `gamescope <gamescope-params> -- env MESA_LOADER_DRIVER_OVERRIDE=zink <game>` which may translate opengl stuff in a game to vulkan, which then allows gamescope to bypass Xwayland

**Comment by yellowsink** [comment]
This bug goes away for me when unsetting the LD_PRELOAD env var for the gamescope process (eg steam launch command like `env LD_PRELOAD="" gamescope -w 1920 -h 1080 -f -- %command%`)

**Comment by Etmix** [comment]
> This bug goes away for me when unsetting the LD_PRELOAD env var for the gamescope process (eg steam launch command like `env LD_PRELOAD="" gamescope -w 1920 -h 1080 -f -- %command%`)

Thank you! This fixes the issue for me.
Enabling the overlay and adding "-e" did not work.

**Comment by Mentalgen** [comment]
What's LD_PRELOAD being set to that's causing this then?

**Comment by jbellionjourdan** [comment]
Not sure if it can help, but on my end this issue triggers only when `--mangoapp` is set.

When the game starts stuttering, hiding mangohud with RALT+F12 helps lowering the issue by ~75% but doesn't make it disappear.

Removing the `--mangoapp` flag when launching the game makes it completely disappear, i can play for one hour straight or more without any stuttering after the ~20min mark.

**Comment by Forge64** [comment]
> > > In gamemode.ini file i set renice to 10
> > 
> > 
> > 10 or -10? Higher nice value means lower priority.
> 
> Accodin to this webside (you are wrong) https://gamecrate.com/linux-gaming-boost-your-performance-gamemode/25200 Quote "f you have four or more CPU cores. I like to set the “renice” value at “10” - this will increase the priority of your game’s process, telling Linux to prioritize the game’s CPU time."

For internet reference, the website linked was wrong. Quoting the nice manpage:

Run COMMAND with an adjusted niceness, which affects process scheduling.  With no COMMAND, print  the  current  niceness.   Niceness  values  range  from  -20 (most favorable to the process) to 19 (least favorable to the process).

**Comment by kagadar** [comment]
> > > > In gamemode.ini file i set renice to 10
> > > 
> > > 
> > > 10 or -10? Higher nice value means lower priority.
> > 
> > 
> > Accodin to this webside (you are wrong) https://gamecrate.com/linux-gaming-boost-your-performance-gamemode/25200 Quote "f you have four or more CPU cores. I like to set the “renice” value at “10” - this will increase the priority of your game’s process, telling Linux to prioritize the game’s CPU time."
> 
> For internet reference, the website linked was wrong. Quoting the nice manpage:
> 
> Run COMMAND with an adjusted niceness, which affects process scheduling. With no COMMAND, print the current niceness. Niceness values range from -20 (most favorable to the process) to 19 (least favorable to the process).

And to close the loop on this, the website was _not_ wrong, you just missed the context about where the value is being used. Gamemode's config negates whatever `renice` value is provided, so a positive value means higher priority: https://github.com/FeralInteractive/gamemode/blob/086b3fe5b4e9ec58e419a80bf395bea681d9b510/example/gamemode.ini#L28

**Comment by Forge64** [comment]
> > Replying to [#163 (comment)](https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-2494645457)
> 
> And to close the loop on this, the website was _not_ wrong, you just missed the context about where the value is being used. Gamemode's config negates whatever `renice` value is provided, so a positive value means higher priority: https://github.com/FeralInteractive/gamemode/blob/086b3fe5b4e9ec58e419a80bf395bea681d9b510/example/gamemode.ini#L28

I don't see how the website can be right, unless you have to be logged in to see content or other such nonsense. The link here sends me to the base url on Firefox and Chrome both, with no content displayed, only links to ads and articles not related to the thread subject.

Gamemode's configuration option should perhaps be changed, to avoid such confusion in the future? If it's not truly a "nice" value, but an inverted modifier to nice, perhaps "nice_modifier" would be less unclear.

I am all for RTFM'ing, but being less unclear when the option is presented at little to no cost is also desirable, IME.

**Comment by KarlVogel** [comment]
Likely related https://github.com/ValveSoftware/steam-for-linux/issues/11446

**Comment by Gibbz** [comment]
I'm getting this bug with factorio after about 30 mins. Is there a planned fix? 

I'll try the workaround!

**Comment by justin8** [comment]
For those who are dealing with this issue still, a workaround that has resolved the issue for me in the meantime across 5+ games is:

Set your launch options to `LD_PRELOAD="" %command%`. It can possibly cause some issues with steam overlay if you have that enabled for certain games; but the stuttering is completely gone.

**Comment by AngelBePro** [comment]
I have had the steam overlay on without LD_PRELOAD="" for about a hour now in CS2 with gamescope and have not gotten this issue. Can someone else confirm that this has been fixed?

**Comment by andradei** [comment]
I just got stuttering with Deep Rock Galactic and Cat Quest 2.

**Comment by Znephf** [comment]
I encountered the bug on Manjaro KDE using gamescope for dota2. I did not encounter this bug with x11 but now after switching to wayland i get the same bug as described here. Is there any reason why im encountering this bug with wayland but not with x11?

**Comment by SergSel2006** [comment]
> Replying to https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-2494645457

The fact that gamemode negates the config value and then applies nice value ironically makes the site right, but for the wrong reason. 
Source: https://github.com/FeralInteractive/gamemode/blob/master/example/gamemode.ini
By the way, I also got the same issue with all of my game library. The workaround worked.

**Comment by THENATHE** [comment]
After the beta update that supposedly fixes this issue, I was still having this issue. My launch params were 

`gamemoderun gamescope --mangoapp -w 2560 -h 1440 -r 144 -f -- %command%`

Removing `--mangoapp` significantly delayed this for me, but did not solve it. Problem does not exist with gamescope disabled

Steam overlay ON, recording set to manual but I'm not sure if that matters. 
5800x3d, 9070xt, 64gb ram, Arch linux 6.15.6-arch1-1 mesa 1.25.1.6-1 kde plasma 6.4.3 (wayland)

**Comment by Doc-4** [comment]
This definitely still exists on stable. CachyOS, near vanilla, nvidia with latest drivers. On infra (appid 251110) the leg bar goes off at around 20 to 40 minutes and it's very visually apparent, like gamescope is stuttering in old frames in between current ones, and about halved frame rate. On something more recent like Helldivers 2 (553850) it took several hours and wasn't as visually broken but still knocked off 1/3-1/2 the frame rate.

My launch parameters were this: 
game-performance gamescope -w 2560 -h 1440 -f --expose-wayland --adaptive-sync --force-grab-cursor -- %command%
 with helldivers 2 additionally having HDR exposed, but the bug happens with as minimal settings as just resolution and fullscreen. Game settings do not seem to matter. Using the LD_preload= env fixes the issue.

Notably, I've mostly tried this with steam overlay on, so this occurs regardless if the overlay is on or not. Setting preload to nothing also disables the overlay, which is annoying. 

Is this bug purportedly only fixed in the beta or something?

**Comment by hyperdotbat** [comment]
> Is this bug purportedly only fixed in the beta or something?

I'm experiencing this on the Beta Steam Client, Vanilla Arch

**Comment by Caier** [comment]
Happened to me as well while playing Worms Armageddon (217200), and the `LD_PRELOAD=""` workaround also helped.

arch 6.17.4, hyprland 0.51.1

**Comment by aimaismog** [comment]
This seems to be present in Geometry Dash as well after approx 60 minutes or less. FPS for me goes from the cap of 292 to horrendous frame times and 172 FPS, and scales accordingly with frame rate for some reason... Weird.
Arch 6.17.5 and Niri 25.08-2

**Comment by wimgoeman** [comment]
Same problem in Split Fiction for me. RTX2070, Endeavor OS. Found it in Hyprland, and found same issue in Plasma, before finding this Github issue. LD_PRELOAD="" workaround fixed it.

**Comment by RainOrigami** [comment]
This has been an ongoing issue for me. Since I am using hyprland it's better to run games in gamescope. This way it can be easily grabbed by a hyprland window rule to put it on a specific monitor and workspace, lock the resolution and keep the cursor from moving onto other monitors. A lot of games do not play well with a tiling window manager or multiple monitors and cause the strangest behaviours, especially bad when they have a splash screen or your left most screen is not your primary screen. Also many games, like Arma Reforger or Peak, are horrendous when it comes to keeping the mouse cursor inside of the game window making them near unplayable without gamescopes force-grab-cursor.

For some games (eg. Sandustry Demo) using gamescope (`gamemoderun gamescope -f -w 2560 -h 1440 -W 2560 -H 1440 -r 165 --force-grab-cursor --framerate-limit 165 --force-windows-fullscreen -- %command%`) after like 20-30 minutes cause a wavy kind of lag, like every 30 frames is a slow frame. This is visible in mangohud (when enabled) where there are periodic spikes in the graph. Other games, like Rocket League (same command) work perfectly fine.

For games that have this issue I have to either resort to not running them in gamescope or using the LD_PRELOAD workaround which disables the steam overlay. Both workarounds are not very good.

I hope Valve can identify and solve this issue eventually, it's been going on for a while.

EndeavourOS x86_64 6.17.9-zen1-1-zen, Hyprland 0.52.1, NVIDIA GeForce RTX 4090, AMD Ryzen 9 7900X, 64GB RAM. Steam Version: 1763795278 from multilib/steam. Gamescope version 3.16.17-1 from extra/gamescope.
/proc/cmdline: `initrd=\...\6.17.9-zen1-1-zen\initrd nvme_load=YES nowatchdog rw rootflags=subvol=/@ root=UUID=... resume=UUID=... nvidia_drm.modeset=1 systemd.machine_id=...`

**Comment by RheaAyase** [comment]
Common issue, 100% reproducibility, not being fixed for years. Oh well.

**Comment by tpsteiner** [comment]
+1 This is a very frustrating issue, since your game will become unplayable at the worst time. If I weren't so stubborn, this is the issue that would push me back to Windows gaming.

**Comment by redyf** [comment]
LD_PRELOAD="" worked for me, thank you!

**Comment by brettns** [comment]
LD_PRELOAD="" has a massive side effect of stopping the controller/gamepad from working. Is there a way to prevent the lag bomb and still have a working controller?

**Comment by Doc-4** [comment]
@brettns you can sidestep the issue by installing a driver for your controller (xone for Xbox, etc) and disabling Steam Input for that game, which does mean no rebinding via it. Outside of that, no, nothing I've tried. Perhaps downgrade gamescope and experiment if you prefer that route?

**Comment by brettns** [comment]
Thanks for the quick reply @Doc-4 . I have an xbox controller connected via bluetooth and am using xpadneo driver which I thought was how my controller was working - it also works with non steam games using Heroic Launcher - but I have no idea what steam is doing with my controller. All I know is that it stops working when I set LD=PRELOAD="". I tried both disabling and forcing steam input but that didn't change anything.

**Comment by jarrard** [comment]
> LD_PRELOAD="" has a massive side effect of stopping the controller/gamepad from working. Is there a way to prevent the lag bomb and still have a working controller?

Well I believe enabling the Steam Overlay for said game resolves the issue no?  
This whole problem happens due to overlay being disabled for the game; in my testing.

**Comment by brettns** [comment]
<img width="352" height="157" alt="Image" src="https://github.com/user-attachments/assets/3f70d905-522f-47cb-8066-9d1b69a5dfd3" />

I have the steam overlay enabled here, you can see the steam FPS counter behind mangohud, and it's still doing the lag bomb after 20-30 minutes.

**Comment by jarrard** [comment]
Just be aware that MangoHud can cause issues itself so you should also test with that disabled just to be sure its not interfering. 

Also run Steam in a terminal window and check the debug output and see what is spamming during the slow down.  
Last time I checked it was just a insane looping request for some missing library.  
(Not sure if it needs any debug mode enabled for steam or proton, maybe basic debug output)

**Comment by brettns** [comment]
I had two of the below messages show up in the steam output almost immediately, but with no side effects. Then waited 25mins and as soon as the stutter kicked in, I saw a bunch of them spammed into terminal (Steam overlay is enabled):

[gamescope] [Error] xdg_backend: Compositor released us but we were not acquired. Oh no.

<img width="1015" height="1358" alt="Image" src="https://github.com/user-attachments/assets/bb5e42d9-02bf-4a8a-ab7c-101c30183c66" />

**Comment by jarrard** [comment]
And you don't get this issue without gamescope?

Also I think gamescope has a wayland mode, forgot the argument, but would that help?    --backend wayland

also wayland SDL driver.  > SDL_VIDEODRIVER=wayland

**Comment by Doc-4** [comment]
Yes, unlike older reports I've had the lag bomb be present regardless of the overlay's configuration. All I can say is to go into steam and disable steam input for Xbox type controllers, if that doesn't work then gamescope is probably the weakest link, cut it instead. I've done the same for now, I only use it for a few non-steam games, its ability to properly render HDR has been broken for a while on up to date versions, and then there's the lag bomb.

**Comment by brettns** [comment]
It seems that removing --mangoapp has fixed the lag bomb after 25 minutes with steam overlay enabled.

**Comment by Doc-4** [comment]
In my case last I'd tested it, I'd not disabled the overlay or used mangohud. I'll try it again shortly, maybe they've fixed HDR by now? I just got used to VK_HDR_LAYER and using wine wayland on arch with KDE Plasma. It breaks the overlay, but no lag bomb.

**Comment by Reycko** [comment]
Same issue occuring on Portal 2 (-vulkan) after 24 minutes as exactly like in this issue

**Comment by kamild1996** [comment]
I've been experiencing this issue on CachyOS (with KDE Plasma), in Team Fortress 2 running natively, using the following launch options:
`DXVK_FRAME_RATE=240 gamescope -W 1920 -H 1080 -r 270 -f --force-grab-cursor --adaptive-sync -mangoapp -- %command% -novid -nohltv -particles 1 -no_texture_stream`
Tricks related to using LD_PRELOAD or enabling Steam Overlay (which has already been on in my case) did not help, but just like somebody else suggested, removing --mangoapp helped. It seems like it collides with Gamescope in some way.

**Comment by thatAkiraFox** [comment]
I'm having this exact issue with Euro Truck Simulator 2. My launch option string is:

```
DXVK_HUD=compiler gamescope -W 1920 -H 1200 -f -b --backend wayland --expose-wayland -- env LD_PRELOAD="$LD_PRELOAD" %command% -nointro
```

1. I'm using the wayland backend to fix an issue where my gamepad input would stutter (yup, not lag, stutter)
2. Also as you can see I'm using the `LD_PRELOAD` workaround listed on the Arch wiki, but still the game starts stuttering heavily after around 20 minutes of gameplay, forcing me to restart it

**Comment by thatAkiraFox** [comment]
> Replying to https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-4168848276

Well quick update, I reduced the string to just `DXVK_HUD=compiler gamescope -W 1920 -H 1200 -f -- %command% -nointro` and it didn't stutter for more than 20 minutes, also there was no gamepad input lag/stutter so... was it caused by the borderless flag? 

No idea, also keep in mind that ETS2 is very, VERY buggy in general, both on Windows and on Linux so probably not the best test subject, but that's that.

**Comment by j00sebox** [comment]
Setting LD_PRELOAD="" works for me but I like using the steam overlay so I made a script that does a little workaround.

```
#!/bin/bash
SAVE="$LD_PRELOAD"
export LD_PRELOAD=""
exec gamescope -W 2560 -H 1440 -f --force-grab-cursor -- env LD_PRELOAD="$SAVE" "$@"
```

For some reason preloading it is the problem. I just run the script in the launch options and everything seems to work fine

**Comment by kamild1996** [comment]
I have also received this command line from somebody on Discord, and it seems to have worked great for me:
`env -u LD_PRELOAD gamescope -W 1920 -H 1080 -f --adaptive-sync --mangoapp --force-grab-cursor -- env LD_PRELOAD="$LD_PRELOAD" %command%`

**Comment by RainOrigami** [comment]
https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-4199660364
> Setting LD_PRELOAD="" works for me but I like using the steam overlay so I made a script that does a little workaround.
> 
> ```
> #!/bin/bash
> SAVE="$LD_PRELOAD"
> export LD_PRELOAD=""
> exec gamescope -W 2560 -H 1440 -f --force-grab-cursor -- env LD_PRELOAD="$SAVE" "$@"
> ```
> 
> For some reason preloading it is the problem. I just run the script in the launch options and everything seems to work fine

This is a great workaround that prevents the stuttering yet enabling mango and steam overlay with no issues on my system. I suspect the solution from @kamild1996 works similarly but I prefer a centralised startup script like above anyways. Thanks for sharing!

For completeness here is my setup:

### ~/.local/bin/run_steam_game.sh (u|=x)
> ```
> #!/bin/bash
> SAVE="$LD_PRELOAD"
> export LD_PRELOAD=""
> LD_BIND_NOW=1 exec gamemoderun gamescope -f -w 2560 -h 1440 -W 2560 -H 1440 -r 165 --force-grab-cursor --framerate-limit 165 --force-windows-fullscreen --mangoapp -- env LD_PRELOAD="$SAVE" "$@"
> ```

### Steam game properties > General > Launch options
> `/home/user/.local/bin/run_steam_game.sh %command%`

**Comment by felipec** [comment]
I used to have a similar issue without gamescope, but only with the steam overlay disabled: ValveSoftware/steam-for-linux#11446. But that issue is now fixed.

I tried to reproduce this issue using gamescope and I managed to do it in hyprland, but not in Xorg. Also, it happens with `--backend wayland`, but not `--backend sdl`. So this seems to be specific to the wayland backend.

Moreover, without `--mangoapp` I cannot reproduce the problem.

**Comment by Doc-4** [comment]
> I have also received this command line from somebody on Discord, and it seems to have worked great for me: `env -u LD_PRELOAD gamescope -W 1920 -H 1080 -f --adaptive-sync --mangoapp --force-grab-cursor -- env LD_PRELOAD="$LD_PRELOAD" %command%`

I used this format, as not every game I use with gamescope needs or wants the same arguments, so scripting it would not necessarily save typing. After a few hours, seems to work well!

**Comment by Jas0rz** [comment]
> I have also received this command line from somebody on Discord, and it seems to have worked great for me: `env -u LD_PRELOAD gamescope -W 1920 -H 1080 -f --adaptive-sync --mangoapp --force-grab-cursor -- env LD_PRELOAD="$LD_PRELOAD" %command%`


i had this problem in Fable anniversary without `--magoapp`, and after an hour+ of testing adding the above before and after the gamescope command in the launch options seems to have fixed the problem. 

i first found this solution on the archwiki but the suggested commands appear to be wrong:
https://wiki.archlinux.org/title/Gamescope#:~:text=launching%20gamescope%20from%20steam%2C%20stuttering%20after%20~24%20minutes%20(gamescope%20lag%20bomb)

**Comment by forgotthepen** [comment]
Got this issue recently as soon I started using gamescope inside steam, happy 2026 everyone! 🥳 

```ini
OS = Fedora Linux 44
Kernel = 7.0.9
DE = KDE Plasma 6.6.5
WM = KWin (Wayland)
GPU = NVIDIA with driver 595.71
```

Credits to the [original solution](https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-2143491396) and [this script](https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-4199660364).
I wanted something that acts as a drop-in replacement for `gamescope` executable only, without any specific flags or configutaions because I use various options on different games, so I came up with this script.

Save it for exmaple in `~/my/scripts/steam-gamescope.sh`, then make it available system wide
```shell
sudo ln -s ~/my/scripts/steam-gamescope.sh /usr/bin/steam-gamescope
sudo chmod +x /usr/bin/steam-gamescope 
```

Then inside steam replace `gamescope` with `steam-gamescope`

<details>
<summary>Example</summary>
  
<img width="1118" height="384" alt="Image" src="https://github.com/user-attachments/assets/7a87c770-117d-417d-870d-21d4b33198bb" />
  
</details>

Here's the script, I'm additionally unsetting `LD_LIBRARY_PATH` so `gamescope` (not the game itself) won't magically pick up paths for dynamic libraries, if that's problematic on your end you can remove that part.
<details>
  
```shell
#!/usr/bin/env bash

# https://github.com/ValveSoftware/gamescope/issues/163
# discussion: https://www.linux.org/threads/problem-with-gamescope-stuttering.36926/
# original solution: https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-2143491396
# original script: https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-4199660364

if ! command -v gamescope &>/dev/null; then
  echo "X gamescope executable is missing" >&2
  exit 1
fi

org_ld_preload="$LD_PRELOAD"
org_ld_library_path="$LD_LIBRARY_PATH"

MY_ARGS=()

while [[ $# -gt 0 ]]; do
  if [[ "$1" = "--" ]]; then
    shift 1
    break
  fi

  MY_ARGS+=("$1")
  shift 1
done

if [[ $# -le 0 ]]; then
  echo "X missing game executable/arguments" >&2
  exit 1
fi

LD_PRELOAD="" LD_LIBRARY_PATH="" exec gamescope \
  "${MY_ARGS[@]}" \
  -- \
  env \
    LD_PRELOAD="$org_ld_preload" \
    LD_LIBRARY_PATH="$org_ld_library_path" \
  "$@"
```

</details>

**Comment by PolygonError** [comment]
> Responding to [comment #4550014274](https://github.com/ValveSoftware/gamescope/issues/163#issuecomment-4550014274)

works great thanks

I had to change the line settings gamescope's LD_PRELOAD as below to get gamemode working again:
```bash
LD_PRELOAD="/usr/\$LIB/libgamemode.so.0" LD_LIBRARY_PATH="" exec gamescope \
  "${MY_ARGS[@]}" \
  -- \
  env \
    LD_PRELOAD="$org_ld_preload" \
    LD_LIBRARY_PATH="$org_ld_library_path" \
  "$@"
```

**Comment by malucard** [comment]
I'm having this issue in Deadlock, but the stutter only happens on keyboard input. Looking around is smooth, but eg. holding a key to walk makes it stutter like crazy. Checking CPU usage when the bug is active, I also notice the `steam` process is using over 300% CPU. Normally, when the bug isn't active yet, it's sitting at under 2%.

**Comment by gordan-ramsey** [comment]
Can confirm that LD_PRELOAD="" fixed the issue for me in Pop_OS! 24.04.
Also the issue only appears to be when you use gamescope combined with an Nvidia GPU (RTX 3060 in my case).
I have not seen it happen with my laptop that has AMD Ryzen 7 AI Radeon 860M

**Comment by PolygonError** [comment]
> Also the issue only appears to be when you use gamescope combined with an Nvidia GPU

Definitely not, I have a RX 9070 XT and this issue occurs

**Comment by hadronized** [comment]
I concur with @PolygonError ; I have a Radeon RX 7800 XT, same issue.

**Comment by tectrixdev** [comment]
> Can confirm that LD_PRELOAD="" fixed the issue for me in Pop_OS! 24.04. Also the issue only appears to be when you use gamescope combined with an Nvidia GPU (RTX 3060 in my case). I have not seen it happen with my laptop that has AMD Ryzen 7 AI Radeon 860M

I have seen it happen on my ryzen AI 7 350 laptop.

**Comment by St0nefish** [comment]
Still present on **gamescope 3.16.25** (current release). Posting a quantified frametime trace, since most of this thread is necessarily qualitative and I think that's part of why it's hard to action.

<details><summary>

**The short version:** average FPS stays healthy the entire time. The failure is invisible to every average-based metric, including mangoapp's own FPS readout. Only the frametime *maximum* catches it.

</summary>

### Environment

| | |
|---|---|
| gamescope | 3.16.25-1.1 |
| GPU | NVIDIA RTX 5090 |
| Driver | 610.57.04 (open kernel modules) |
| Kernel | 7.1.6 (CachyOS) |
| Compositor | KDE Plasma 6.7.3 / KWin, Wayland session |
| Backend | Wayland (nested, xdg_backend) |
| CPU | Ryzen 7 7800X3D |
| Game | Bloons TD 6 (Unity, D3D11 via DXVK) |
| Proton | GE-Proton10-26 |

Launch args:

```text
gamescope -W 3440 -H 1440 -r 240 -f --immediate-flips --rt --mangoapp --hdr-enabled -- %command%
```

Fullscreen at native resolution (gamescope logs `edid: Patching res 800x1280 -> 3440x1440`). Display is 3440x1440 @ 240 Hz.

### Method

MangoHud logging to CSV, 1 sample/sec, ~31 minutes of normal play, analysed afterwards.

Worth stating: the degradation is **immediately and unmistakably obvious while playing**. I called it out in real time, before looking at any of this data, and the moment I flagged it matches the logged onset below. The subjective and objective signals agree — this is not a marginal effect that only shows up in a graph.

### Data

Frametime distribution per 2-minute window. Frame budget at 240 Hz is 4.17 ms; 8.3 ms is a doubled frame:

```text
min  0- 2  n=239   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.63 ms
min  2- 4  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.41 ms
min  4- 6  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.41 ms
min  6- 8  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.38 ms
min  8-10  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.41 ms
min 10-12  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.38 ms
min 12-14  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  6.27 ms
min 14-16  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  5.41 ms
min 16-18  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  5.19 ms
min 18-20  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  6.05 ms
min 20-22  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.56 ms
min 22-24  n=240   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.55 ms
min 24-26  n=240   >8.3ms:   5   >16.7ms:   5   >33ms:   4    max 54.70 ms   <-- onset
min 26-28  n=240   >8.3ms:   8   >16.7ms:   8   >33ms:   8    max 54.78 ms
min 28-30  n=240   >8.3ms:   5   >16.7ms:   5   >33ms:   5    max 54.88 ms
min 30-32  n=136   >8.3ms:   0   >16.7ms:   0   >33ms:   0    max  4.50 ms
```

Percentiles across the degraded region (min 24–30, n=720):

```text
p50 =  4.15 ms
p90 =  4.30 ms
p99 = 54.40 ms
max = 54.88 ms
```

### Observations

**1. Onset is binary, not gradual.** Zero frames exceed 8.3 ms across the first 24 minutes (2,879 consecutive samples). From minute 24 onward the stalls appear immediately and persist. There is no ramp.

**2. The stall magnitude is suspiciously consistent** — 54.70 / 54.78 / 54.88 ms across three consecutive windows. That regularity suggests a specific periodic stall rather than general scheduling jitter. ~54.8 ms is roughly 13 missed refreshes at 240 Hz.

**3. Averages completely hide it.** Average FPS over the same windows moves only ~430 → ~266, and p50 frametime never budges from ~4.15 ms. If you measure with average FPS — which is what mangoapp displays — nothing appears wrong at any point. I suspect this is why reports get dismissed as subjective. The p50/p99 split (4.15 vs 54.40) is the tell.

**4. Where to look — and why 1% lows miss it.** Corrected for length bias (time-uniform sampling over-represents long frames), the stalls are only **0.173% of frames** while occupying **2.4% of wall-clock time**. That puts them *below* the 1% threshold: `fps_metrics=0.01` reads ~230 fps and shows nothing. `fps_metrics=0.001` (0.1% low) does catch it, at ~18 fps. So the standard stutter metric — 1% lows — is blind to this by construction, as is average FPS. Frametime max/p99 and 0.1% lows are what surface it. Matches what I saw live: running `fps_metrics=0.01`, nothing on the HUD indicated a problem while the stutter was plainly visible.

**5. The GPU is idle when it happens.** Sampled during the degraded period: 9% utilisation, P3 power state, 88 W, SM clock 1845 MHz. This is not a load or thermal issue — the GPU has nothing to do and frames still aren't landing. Points at frame presentation/pacing.

**6. Sampling caveat — the real rate is much higher.** Logging is 1 Hz against ~250 fps, so each row samples roughly one frame in 250. Catching 5–8 stalls per 240 samples implies ~2% of all frames are affected, i.e. on the order of several stalls per second. The raw counts above understate the frequency by a large factor.

The final window returning to zero is the session ending — I closed the game there (n=136, partial window). It is **not** a recovery; the stalls persisted until I quit.

### Control: does not occur without gamescope

I have hundreds of hours across many games on this exact stack **minus gamescope** and have never seen this behaviour once. Single-variable isolation — same hardware, driver, kernel, compositor, game and settings, toggling only gamescope — reproduces it **100% of the time** when gamescope is enabled.

### Ruled out

- **Not #1384** — zero `xwm: got the same buffer committed twice` warnings in the entire session log.
- **Not #1837** — that was GNOME/Mutter-specific and closed; this is KWin.
- **Not thermal/power** — 49 °C, 88 W at onset.
- **Not load** — 9% GPU utilisation on a very light game.

### Possibly related

gamescope logs these at startup on this driver:

```text
[gamescope] [Error] vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344241 (VkResult: 0)
[gamescope] [Error] vulkan: vkGetPhysicalDeviceFormatProperties2 returned zero modifiers for DRM format 0x38344258 (VkResult: 0)
```

Those are `ABGR2101010` and `XBGR2101010` — the 10-bit formats. NVIDIA returns zero DRM modifiers for both. I don't know whether that's connected to the stall behaviour and I'm not assuming it is — this thread carries reports from AMD users as well, so I'm not claiming vendor-specificity. Noting it only in case it's useful.

Raw CSV (3,218 rows) available on request.

</details>

**Comment by cain-dev** [comment]
RX 7600 here, same issue. gamescope version 3.16.25 (gcc 16.1.1)

**Comment by felipec** [comment]
I built gamescope with e399345 and I can confirm that on hyprland with `--backend wayland` the stutter after 30 minutes no longer appears.
