### ISSUE TITLE
Major stuttering on KDE 5.26

### ISSUE THREAD

**Issue by zany130** [Plagman/gamescope#657]
Ever since the KDE 5.26 update gamescope has causes major stutter in all games, I have tested. Downgrading back to 5.25.5 fixes the issue

Sys info:
```
inxi -b
System:
  Host: Garuda-Linux Kernel: 6.0.1-270-tkg-bmq arch: x86_64 bits: 64
    Desktop: KDE Plasma v: 5.26.1 Distro: Garuda Linux
Machine:
  Type: Desktop Mobo: ASRock model: X470 Taichi serial: <superuser required>
    UEFI: American Megatrends v: P4.90 date: 05/18/2022
CPU:
  Info: 6-core AMD Ryzen 5 5600X [MT MCP] speed (MHz): avg: 3656
    min/max: 2200/4650
Graphics:
  Device-1: AMD Navi 22 [Radeon RX 6700/6700 XT/6750 XT / 6800M]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.3
    compositor: kwin_wayland driver: X: loaded: amdgpu
    unloaded: modesetting,radeon dri: radeonsi gpu: amdgpu resolution:
    1: 2048x864 2: 1396x785
  OpenGL: renderer: AMD Radeon RX 6700 XT (navi22 LLVM 14.0.6 DRM 3.48
    6.0.1-270-tkg-bmq) v: 4.6 Mesa 22.2.1
Network:
  Device-1: Intel Dual Band Wireless-AC 3168NGW [Stone Peak] driver: iwlwifi
  Device-2: Intel I211 Gigabit Network driver: igb
Drives:
  Local Storage: total: 2.96 TiB used: 4.07 TiB (137.7%)
Info:
  Processes: 450 Uptime: 47m Memory: 31.27 GiB used: 14.33 GiB (45.8%)
  Shell: fish inxi: 3.3.22
  ```

**Comment by zany130** [comment]
found a workaround. removing the `-f` flag and then forcing full screen through kwin rules fixes the stuttering. This was not necessary on 5.25.5 (same game scope version `3.11.47-1` )

**Comment by sonic2kk** [comment]
Can't reproduce with Gamescope from Git abd a 5700XT but I had this problem right up until 5.26, where it was fixed. I reported it in #504. Sounds like an eerily similar issue and probably on KDE's side

**Comment by zany130** [comment]
Yeah your right the two issues are very similar only difference is it only happens in 5.26 (i tired downgrade to 5.25.5 and it fixed the issue). Also,  the gamescope hotkeys (so super+f for full screen for example) do not work for me.

**Comment by IDeathByte** [comment]
>Also, the gamescope hotkeys (so super+f for full screen for example) do not work for me.
try ctrl+super+f. works for me
seems like some hotkeys reserved by plasma

**Comment by zany130** [comment]
yeah found out `super+f` already does something in kde shortcuts (forgot what) after unsetting it gamescope full screen hotkey works. Still get the fullscreen stutter though unless I use kwin rules to set it to open on fullscreen (so fullscreening after the gamescope window was created seems to be whats causing the stutters)

**Comment by zany130** [comment]
can no longer reproduce as of the latest gamescope git

**Comment by imavlr** [comment]
What kind of "stuttering" are you experiencing, steady or fluctuating?

I get this same thing under Sway, using the `-f` flag causes the game to run at a lower, but steady framerate, seems to be about half of what I'd expect (looks higher than 60 but lower than 144). There don't appear to be any fluctuations, and the in-game performance stats show a steady 144 fps, so the game isn't affected, only gamescope.

When launching the game without `-f`, and using meta+f to toggle it afterwards (I believe Sway takes precedence, skipping gamescope's built-in fullscreen method), there is no such issue, it updates at the full 144Hz, and there doesn't appear to be any depreciation in image quality or anything of the sort.

Similar to https://github.com/ValveSoftware/gamescope/issues/504, I play Apex Legends, which has a splash screen that pops up first, for the anti-cheat, after which the game starts, so I wonder if it may be related to games that spawn more than one window, since you can no longer recreate it with vkcube.

**Comment by zany130** [comment]
I haven't been able to reproduce this at all for a while since KDE5.27, but yes, my issue was pretty much the same as what @imavlr was describing

**Comment by Mushoz** [comment]
I am also experiencing major stuttering under a Gnome 44 Wayland session with the -f flag specified. This is with final fantasy XIV, which is also a game that has an initial launcher before the actual game starts, so your notion that the splash screen might be introducing this could be true!

**Comment by Mushoz** [comment]
Seems to be a duplicate of this: https://github.com/ValveSoftware/gamescope/issues/504
